import Head from "next/head";
import { Inter } from "@next/font/google";
import Banner from "../components/Banner";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Movie Next</title>
        <meta name="description" content="Generated by movie next" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Banner />
        </div>
      </main>
    </>
  );
}
